name: CI/CD - Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checa o repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Configura login no DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-k8s-observability:latest ./app

      # 4. Push da imagem para DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-k8s-observability:latest
